[WIP] Add flag support and refactor code
kinvolk/fanotify-experiments pull request #8
Opened 2022-04-20 08:28 UTC by knrt10

2022-04-20 08:36 UTC, knrt10 commented
@surajssd, the code is building fine but not working. Looking into it. Can you please check if this is the correct layout for packages?

2022-04-21 11:33 UTC, surajssd commented
@knrt10 can you post the errors?

2022-04-21 12:08 UTC, knrt10 commented
@surajssd, fixed. Please review

2022-04-21 13:34 UTC, surajssd requested changes

2022-04-21 13:34 UTC, surajssd commented on cli/cmd/root.go
> +	pf.StringVarP(&kubeconfig, "kubeconfig", "", "~/.kube/config", "Path to kubeconfig")
How about `$HOME/.kube/config` that way we can use os.ExpandEnv?

2022-04-21 13:34 UTC, surajssd commented on internal/util.go
> +	runtimeContainerd = "containerd"
why is one exported and other isn't?

2022-04-21 13:34 UTC, surajssd commented on cli/cmd/root.go
> +	go internal.GetNewPods(pods, hostname, kubeconfig)
How about a k8s package? And this function lives there?

2022-04-21 13:34 UTC, surajssd commented on internal/util.go
> +func CheckRuntime(hostRuntime string) {
this function is a bit misleading. It checks runtime but also modified the containerd namespace.

2022-04-21 13:34 UTC, surajssd commented on pkg/containerd/containerd.go
> +}
This is not containerd specific.

2022-04-21 13:34 UTC, surajssd commented on pkg/containerd/containerd.go
> +}
This is also not containerd specific.

2022-04-21 13:34 UTC, surajssd commented on internal/util.go
> +	return "k8s_" + podName + "_" + cntName + "_" + podNamespace + "_" + podUID, nil
this whole part can be moved to containerd package.

2022-04-22 03:28 UTC, knrt10 commented on internal/util.go
> +	runtimeContainerd = "containerd"
exported both, but the RuntimeDocker was also getting used for checking inside `root.go`.

2022-04-22 03:43 UTC, knrt10 commented
@surajssd, updated. PTAL

2022-04-22 03:52 UTC, knrt10 commented on internal/util.go
> +	runtimeContainerd = "containerd"
Fixed. Moved them to respective packages

2022-04-22 09:46 UTC, surajssd reviewed
Just some nits, otherwise looks good to go.

2022-04-22 09:46 UTC, surajssd commented on README.md
> +      ```
Cluster creation is out of scope of this document.

2022-04-22 09:46 UTC, surajssd commented on cli/cmd/root.go
> +	pf.StringVarP(&hostname, "hostname", "", "", "Name of node in k8s control plane")
It does not have to be control plane, it is just the name of the node on which this app is running.

2022-04-22 11:18 UTC, surajssd approved these changes

2022-04-22 11:19 UTC, merged